name: tests-cluster-standalone

on:
  pull_request:
    branches-ignore:
      - 'gh-pages'

jobs:
  test-cluster-standalone:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Setup kind
        uses: ./.github/actions/setup-kind

      - name: Deploy the operator
        uses: ./.github/actions/deploy-operator

      - name: Install KUTTL
        uses: ./.github/actions/setup-kuttl

      - name: Run KUTTL tests
        run: |
          kubectl kuttl test
